API(2)/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

API(2)/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
     path('admin/', admin.site.urls),
    path('', include('pybo.urls')), 
  
]

API(2)/mysite/pybo/urls.py
from django.urls import path
from django.template import *
from . import views

app_name = 'green'

urlpatterns = [
    path('', views.start, name='start'),
    path('main/', views.main, name='main'),
    path('page1/', views.farm_nm1, name='farm_nm1'),
    path('page2/', views.farm_nm2, name='farm_nm2'),
    path('page2_1/', views.back, name='back'),
   
    
]

API(2)/mysite/common/models.py
from django.db import models

# Create your models here.

API(2)/mysite/pybo/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    
    def __str__(self):
        return self.question.subject
 
# Create your models here.

API(2)/mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
    
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

API(2)/mysite/common/views.py
from django.shortcuts import render

# Create your views here.

API(2)/mysite/pybo/views.py
from django.utils import timezone
import pandas as pd
from django.shortcuts import render, redirect
import requests
import xml.etree.ElementTree as ET
import re
import openpyxl

def start(request):
    return render(request,'pybo/start.html')

def main(request):
    return render(request,'pybo/main.html')

ar = [None, None, None]

def farm_nm1(request):
    global ar
    ar[0] = request.GET.get('q')
    if ar[0] == "광주광역시" or ar[0] == "세종특별자치시" or ar[0] == "제주특별자치도" or ar[0] == "울산광역시":
        df = pd.read_excel('C:\API(2)\mysite\static\data/result4.xlsx', sheet_name='Sheet1')
        # ar[1] 변수에 저장된 값과 '시군구' 컬럼 값이 같은 경우에만 데이터를 필터링합니다.
        if ar[0]:
            df = df[df['ctprvnNm'] == ar[0]]
   
        # 데이터프레임에서 필요한 컬럼만 선택합니다.
        columns = ['exprnVilageNm','rdnmadr','exprnCn','rprsntvNm','phoneNumber','homepageUrl', 'latitude', 'longitude']
        df = df[columns]
        df = df.fillna('없음')
   
        
        # 데이터프레임의 각 row에 대해 리스트를 만들어줍니다.
        data_list = []
        for row in df.itertuples(index=False):
            data_list.append(list(row))
 
        # 위도와 경도를 추출하여 배열에 저장
        locations = [(row[-2], row[-1]) for row in df.itertuples(index=False)]
    
        context = {'data_list': data_list, 'locations': locations}
        return render(request, 'pybo/조회.html', context)

    url = ''.join(['pybo/',ar[0],'.html'])

    return render(request, url)

data_list=[]
def farm_nm2(request):
    global ar
    ar[1] = request.GET.get('w')
    df = pd.read_excel('C:\API(2)\mysite\static\data/result4.xlsx', sheet_name='Sheet1')

    # ar[1] 변수에 저장된 값과 '시군구' 컬럼 값이 같은 경우에만 데이터를 필터링합니다.
    if ar[0]:
        df = df[df['ctprvnNm'] == ar[0]]
    if ar[1]:
        df = df[df['signguNm'] == ar[1]]

    # 데이터프레임에서 필요한 컬럼만 선택합니다.
    columns = ['exprnVilageNm','rdnmadr','exprnCn','rprsntvNm','phoneNumber','homepageUrl', 'latitude', 'longitude']
    df = df[columns]
    df = df.fillna('없음')

    
    # 데이터프레임의 각 row에 대해 리스트를 만들어줍니다.
    data_list = []
    for row in df.itertuples(index=False):
        data_list.append(list(row))
  
    # 위도와 경도를 추출하여 배열에 저장
    locations = [(row[-2], row[-1]) for row in df.itertuples(index=False)]
   

    context = {'data_list': data_list, 'locations': locations}
    return render(request, 'pybo/조회.html', context)

def back(request):
    global ar
    ar[0]=None
    if ar[0] != None:
        url = ''.join(['pybo/',ar[0],'.html'])
       
        return render(request, url)
    else :
        url1 = 'pybo/main.html'
        return render(request,url1)

API(2)/mysite/templates/pybo/강원도.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .image-container {
      position: relative;
    }
    .image {
      position: absolute;
    }
    .image:first-child {
      top: 10px;
      left: 10px;
    }
    .image:last-child {
      top: 220px;
      left: 100px;
    }

    .container {
      position: absolute;
      height: 70vh;
      width: 10vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    #my-table {
      position: absolute;
      top: 223px;
      right: -1000px;
      
    }

  </style>
  


  <div style="position: absolute" >
    <img src="{% static 'img\세부지역1.png'%}">
  </div> 
  
  <div class="container2">
    <a href="{% url 'green:back'%}">
      <img src="{% static 'img\back.png'%}">
    </a>
  </div>

  <div class="container">
    <table  width ="1000" height="350"  id= "my-table">
      <tr align="center">
        <td style= "padding : 10px">
         <a href="{% url 'green:farm_nm2'%}?w=강릉시">
           <img src="{% static 'img\강원도\강릉시.png'%}"></a>
      </td>
      <td style= "padding : 10px">
        <a href="{% url 'green:farm_nm2'%}?w=고성군">
          <img src="{% static 'img\강원도\고성군.png'%}"></a>
      </td>
   
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=동해시">
             <img src="{% static 'img\강원도\동해시.png'%}"></a>
        </td>
      </tr>
        
      <tr align="center">
      <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=삼척시">
             <img src="{% static 'img\강원도\삼척시.png'%}"></a>
        </td>
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=속초시">
             <img src="{% static 'img\강원도\속초시.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=양구군">
             <img src="{% static 'img\강원도\양구군.png'%}"></a>
        </td>
      </tr>

      <tr align="center">
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=양양군">
            <img src="{% static 'img\강원도\양양군.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=영월군">
            <img src="{% static 'img\강원도\영월군.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?r=원주시">
            <img src="{% static 'img\강원도\원주시.png'%}"></a>
        </td>
      </tr>

      <tr align="center">
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=인제군">
             <img src="{% static 'img\강원도\인제군.png'%}"></a>
        </td>
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=정선군">
             <img src="{% static 'img\강원도\정선군.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=철원군">
             <img src="{% static 'img\강원도\철원군.png'%}"></a>
        </td>
      </tr>

      <tr align="center">
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=춘천시">
             <img src="{% static 'img\강원도\춘천시.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=태백시">
             <img src="{% static 'img\강원도\태백시.png'%}"></a>
        </td>
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=평창군">
             <img src="{% static 'img\강원도\평창군.png'%}"></a>
        </td>
      </tr>

      <tr align="center">
        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=홍천군">
             <img src="{% static 'img\강원도\홍천군.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=화천군">
             <img src="{% static 'img\강원도\화천군.png'%}"></a>
        </td>

        <td style= "padding : 10px" >
            <a href="{% url 'green:farm_nm2'%}?w=횡성군">
             <img src="{% static 'img\강원도\횡성군.png'%}"></a>
        </td>
      </tr>
    <div class="container1">
      <a href="{% url 'green:start'%}">
        <img src="{% static 'img\home1.png'%}">
      </a>
    </div>

{% endblock%}

API(2)/mysite/templates/pybo/경기도.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .image-container {
      position: relative;
    }
    .image {
      position: absolute;
    }
    .image:first-child {
      top: 10px;
      left: 10px;
    }
    .image:last-child {
      top: 220px;
      left: 100px;
    }

    .container {
      position: absolute;
      height: 70vh;
      width: 10vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    #my-table {
      position: absolute;
      top: 223px;
      right: -980px;
    }
  </style>
  


  <div style="position: absolute" >
    <img src="{% static 'img\세부지역1.png'%}">
  </div> 

  
  <div class="container2">
    <a href="{% url 'green:back'%}">
      <img src="{% static 'img\back.png'%}">
    </a>
  </div>

  <div class="container">
    <table  width ="1000" height="350"  id= "my-table">
      <tr align="center">
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=가평군">
            <img src="{% static 'img\경기도\가평군.png'%}"></a>
      </td>
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=광주시">
            <img src="{% static 'img\경기도\광주시.png'%}"></a>
      </td>
   
        <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=고양시">
          <img src="{% static 'img\경기도\고양시.png'%}"></a>
        </td>
      
      </tr>
      <tr align="center">
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=시흥시">
            <img src="{% static 'img\경기도\시흥시.png'%}"></a>
        </td>
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=안산시">
            <img src="{% static 'img\경기도\안산시.png'%}"></a>
        </td>
     
          <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=안성시">
            <img src="{% static 'img\경기도\안성시.png'%}"></a>
          </td>
        </tr>  

      <tr align="center">
            <td style= "padding : 10px">
              <a href="{% url 'green:farm_nm2'%}?w=양주시">
                <img src="{% static 'img\경기도\양주시.png'%}"></a>
            </td>
            <td style= "padding : 10px">
              <a href="{% url 'green:farm_nm2'%}?w=여주시">
                <img src="{% static 'img\경기도\여주시.png'%}"></a>
            </td>
         
            <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=연천군">
                <img src="{% static 'img\경기도\연천군.png'%}"></a>
              </td>
            </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=오산시">
                  <img src="{% static 'img\경기도\오산시.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=용인시">
                  <img src="{% static 'img\경기도\용인시.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=이천시">
                  <img src="{% static 'img\경기도\이천시.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=파주시">
                <img src="{% static 'img\경기도\파주시.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=평택시">
                  <img src="{% static 'img\경기도\평택시.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=포천시">
                  <img src="{% static 'img\경기도\포천시.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=화성시">
                  <img src="{% static 'img\경기도\화성시.png'%}"></a>
            </td>
        </tr>
      <div class="container1">
        <a href="{% url 'green:start'%}">
          <img src="{% static 'img\home1.png'%}">
        </a>
      </div>      
{% endblock%}

API(2)/mysite/templates/pybo/경상남도.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .image-container {
      position: relative;
    }
    .image {
      position: absolute;
    }
    .image:first-child {
      top: 10px;
      left: 10px;
    }
    .image:last-child {
      top: 220px;
      left: 100px;
    }

    .container {
      position: absolute;
      height: 70vh;
      width: 10vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    #my-table {
      position: absolute;
      top: 223px;
      right: -980px;
    }
  </style>
  


  <div style="position: absolute" >
    <img src="{% static 'img\세부지역1.png'%}">
  </div> 

  <div class="container2">
    <a href="{% url 'green:back'%}">
      <img src="{% static 'img\back.png'%}">
    </a>
  </div>
  <div class="container">
    <table  width ="1000" height="350"  id= "my-table">
      <tr align="center">
      <td style= "padding : 10px">
        <a href="{% url 'green:farm_nm2'%}?w=의령군">
          <img src="{% static 'img\경상남도\의령군.png'%}"></a>
      </td>
      <td style= "padding : 10px">
        <a href="{% url 'green:farm_nm2'%}?w=진주시">
          <img src="{% static 'img\경상남도\진주시.png'%}"></a>
      </td>
   
        <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=창녕군">
          <img src="{% static 'img\경상남도\창녕군.png'%}"></a>
        </td>
      </tr>
      <tr align="center">
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=창원시">
            <img src="{% static 'img\경상남도\창원시.png'%}"></a>
        </td>
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=통영시">
            <img src="{% static 'img\경상남도\통영시.png'%}"></a>
        </td>
     
          <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=산청군">
            <img src="{% static 'img\경상남도\산청군.png'%}"></a>
          </td>
        </tr>  

      <tr align="center">
            <td style= "padding : 10px">
              <a href="{% url 'green:farm_nm2'%}?w=사천시">
                <img src="{% static 'img\경상남도\사천시.png'%}"></a>
            </td>
            <td style= "padding : 10px">
              <a href="{% url 'green:farm_nm2'%}?w=양산시">
                <img src="{% static 'img\경상남도\양산시.png'%}"></a>
            </td>
         
            <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=남해군">
                <img src="{% static 'img\경상남도\남해군.png'%}"></a>
              </td>
            </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=밀양시">
                <img src="{% static 'img\경상남도\밀양시.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=거제시">
                <img src="{% static 'img\경상남도\거제시.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=거창군">
                <img src="{% static 'img\경상남도\거창군.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=고성군">
                <img src="{% static 'img\경상남도\고성군.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=김해시">
                <img src="{% static 'img\경상남도\김해시.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=하동군">
                <img src="{% static 'img\경상남도\하동군.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=함양군">
                <img src="{% static 'img\경상남도\함양군.png'%}"></a>
            </td>
            <td style= "padding : 10px" >
                <a href="{% url 'green:farm_nm2'%}?w=합천군">
                <img src="{% static 'img\경상남도\합천군.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=함안군">
                <img src="{% static 'img\경상남도\함안군.png'%}"></a>
            </td> 
        </tr>
      <div class="container1">
        <a href="{% url 'green:start'%}">
          <img src="{% static 'img\home1.png'%}">
        </a>
      </div>      
{% endblock%}

API(2)/mysite/templates/pybo/경상북도.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .image-container {
      position: relative;
    }
    .image {
      position: absolute;
    }
    .image:first-child {
      top: 10px;
      left: 10px;
    }
    .image:last-child {
      top: 220px;
      left: 100px;
    }

    .container {
      position: absolute;
      height: 70vh;
      width: 10vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    
    #my-table {
      position: absolute;
      top: 223px;
      right: -980px;
    }
  </style>
  


  <div style="position: absolute" >
    <img src="{% static 'img\세부지역1.png'%}">
  </div> 


  <div class="container2">
    <a href="{% url 'green:back'%}">
      <img src="{% static 'img\back.png'%}">
    </a>
  </div>

  <div class="container">
    <table  width ="1000" height="350"  id= "my-table">
        <tr align="center">
          <td style= "padding : 10px">
            <a href="{% url 'green:farm_nm2'%}?w=경산시">
              <img src="{% static 'img\경상북도\경산시.png'%}"></a>
          </td>
          <td style= "padding : 10px">
            <a href="{% url 'green:farm_nm2'%}?w=경주시">
              <img src="{% static 'img\경상북도\경주시.png'%}"></a>
          </td>
          <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=고령군">
            <img src="{% static 'img\경상북도\고령군.png'%}"></a>
          </td>
        </tr>

      <tr align="center">
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=구미시">
            <img src="{% static 'img\경상북도\구미시.png'%}"></a>
        </td>
        <td style= "padding : 10px">
          <a href="{% url 'green:farm_nm2'%}?w=군위군">
            <img src="{% static 'img\경상북도\군위군.png'%}"></a>
        </td>
     
          <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=김천시">
            <img src="{% static 'img\경상북도\김천시.png'%}"></a>
          </td>
        </tr>  

      <tr align="center">
            <td style= "padding : 10px">
              <a href="{% url 'green:farm_nm2'%}?w=문경시">
                <img src="{% static 'img\경상북도\문경시.png'%}"></a>
            </td>
            <td style= "padding : 10px">
              <a href="{% url 'green:farm_nm2'%}?w=봉화군">
                <img src="{% static 'img\경상북도\봉화군.png'%}"></a>
            </td>
         
            <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=상주시">
                <img src="{% static 'img\경상북도\상주시.png'%}"></a>
              </td>
            </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=성주군">
                 <img src="{% static 'img\경상북도\성주군.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=안동시">
                 <img src="{% static 'img\경상북도\안동시.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=영덕군">
                 <img src="{% static 'img\경상북도\영덕군.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=영양군">
                 <img src="{% static 'img\경상북도\영양군.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=영주시">
                 <img src="{% static 'img\경상북도\영주시.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=영천시">
                 <img src="{% static 'img\경상북도\영천시.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=예천군">
                 <img src="{% static 'img\경상북도\예천군.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=울진군">
                 <img src="{% static 'img\경상북도\울진군.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=의성군">
                 <img src="{% static 'img\경상북도\의성군.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=청도군">
                 <img src="{% static 'img\경상북도\청도군.png'%}"></a>
            </td>
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=청송군">
                 <img src="{% static 'img\경상북도\청송군.png'%}"></a>
            </td> 
            <td style= "padding : 10px">
                <a href="{% url 'green:farm_nm2'%}?w=칠곡군">
                 <img src="{% static 'img\경상북도\칠곡군.png'%}"></a>
            </td> 
        </tr>

        <tr align="center">
            <td style= "padding : 10px">
               <a href="{% url 'green:farm_nm2'%}?w=포항시">
                 <img src="{% static 'img\경상북도\포항시.png'%}"></a>
            </td>
        </tr>
      <div class="container1">
        <a href="{% url 'green:start'%}">
          <img src="{% static 'img\home1.png'%}">
        </a>
      </div>
{% endblock%}

API(2)/mysite/templates/pybo/대전광역시.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .image-container {
      position: relative;
    }
    .image {
      position: absolute;
    }
    .image:first-child {
      top: 10px;
      left: 10px;
    }
    .image:last-child {
      top: 220px;
      left: 100px;
    }

    .container {
      position: absolute;
      height: 70vh;
      width: 10vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    #my-table {
      position: absolute;
      top: 223px;
      right: -980px;
    }
  </style>
  


  <div style="position: absolute" >
    <img src="{% static 'img\main3.png'%}">
  </div> 

  
  <div class="container2">
    <a href="{% url 'green:back'%}">
      <img src="{% static 'img\back.png'%}">
    </a>
  </div>

  <div class="container">
    <table  width ="1000" height="200"  id= "my-table">
      <tr align="center">
      <td  >
        <a href="{% url 'green:farm_nm2'%}?w=대덕구">
          <img src="{% static 'img\대전광역시\대덕구.png'%}"></a>
      </td>  
      <td >
        <a href="{% url 'green:farm_nm2'%}?w=동구">
          <img src="{% static 'img\대전광역시\동구.png'%}"></a>
      </td>
        <td><a href="{% url 'green:farm_nm2'%}?w=유성구">
          <img src="{% static 'img\대전광역시\유성구.png'%}"></a>
        </td>
      </tr>

      <tr align="center">
        <td><a href="{% url 'green:farm_nm2'%}?w=중구">
            <img src="{% static 'img\대전광역시\중구.png'%}"></a>
          </td>
      </tr>
    <div class="container1">
      <a href="{% url 'green:start'%}">
        <img src="{% static 'img\home1.png'%}">
      </a>
    </div>

{% endblock%}

API(2)/mysite/templates/pybo/부산광역시.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .image-container {
      position: relative;
    }
    .image {
      position: absolute;
    }
    .image:first-child {
      top: 10px;
      left: 10px;
    }
    .image:last-child {
      top: 220px;
      left: 100px;
    }

    .container {
      position: absolute;
      height: 70vh;
      width: 10vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    #my-table {
      position: absolute;
      top: 223px;
      right: -980px;
    }
  </style>
  


  <div style="position: absolute" >
    <img src="{% static 'img\main3.png'%}">
  </div> 

  
  <div class="container2">
    <a href="{% url 'green:back'%}">
      <img src="{% static 'img\back.png'%}">
    </a>
  </div>

  <div class="container">
    <table  width ="1000" height="350"  id= "my-table">
      <tr align="center">
      <td style= "padding : 10px">
        <a href="{% url 'green:farm_nm2'%}">
          <img src="{% static 'img\부산광역시\기장군.png'%}?w=기장군"></a>
      </td>
      <td style= "padding : 10px">
        <a href="{% url 'green:farm_nm2'%}">
          <img src="{% static 'img\부산광역시\강서구.png'%}?w=강서구"></a>
      </td>
      <td style= "padding : 10px" ><a href="{% url 'green:farm_nm2'%}?w=영도구">
          <img src="{% static 'img\부산광역시\영도구.png'%}"></a>
        </td>
      </tr>
    <div class="container1">
      <a href="{% url 'green:start'%}">
        <img src="{% static 'img\home1.png'%}">
      </a>
    </div>


{% endblock%}