UI_UX/API/goo/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from green import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('green.urls')),    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UI_UX/API/goo/green/urls.py
from django.core.checks import messages
from django.urls import path
from . import views
app_name = 'green'
urlpatterns = [
    path('', views.start, name="Initialize"),
    path('Jog/', views.home, name="Jog"),
    path('Spindle/', views.home1, name="Spindle"),
    path('Maintenance/', views.home6, name="Maintenance"),
    path('Tool/', views.home7, name="Tool"),
    
]

UI_UX/API/goo/green/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

UI_UX/API/goo/green/forms.py
from django import forms
from green.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성

UI_UX/API/goo/green/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question,Answer
from .forms import QuestionForm
import pandas as pd
from config import settings
import os

def data_coordinates():
    file_path = os.path.join(settings.STATIC_URL, 'data_jydo', 'all_map.txt')
    data = pd.read_csv(file_path, sep=',')
    j1 = []
    j2 = []
    j3 = []
    j4 = []
    url = []
    for index, row in data.iterrows():
        j1.append(row[0])
        j2.append(row[1])
        j3.append(row[2])
        j4.append(row[3])
        url.append(row[4])
    context = {'zip': zip(j1,j2,j3,j4,url)}
    return context

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    answer.save()
    return redirect('green:detail', question_id=question.id)

def question_create(request):
    form = QuestionForm()
    return render(request, 'green/question_form.html', {'form': form})

def start(request):
    return render(request, 'green/Initialize.html', {})


def home(request):
    return render(request, 'green/Jog.html', {})

def home1(request):
    return render(request, 'green/Spindle.html', {})

def home6(request):
    return render(request, 'green/Maintenance.html', {})

def home7(request):
    return render(request, 'green/Tool.html', {})


# Create your views here.

UI_UX/API/goo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
  <style>
    .screen-transition {
      animation: slide-in 1.5s forwards;
    }
    
    @keyframes slide-in {
      from {
        transform: translateX(100%);
      }
      to {
        transform: translateX(0%);
      }
    }


  .pressable {
    transition: transform 0.1s;
    }
  
  .pressable:active {
    transform: translateY(50px);
    }

  .my-div {
    border: 2px solid red;
    width: 170px;
  }
  .my-div1 {
    border: 2px solid red;
    width: 1280px;
  }  
  .my-div3 {
    border: 2px solid red;
    width: 1000px;
    height: 700px;
    position: absolute; left: 500px; top: 175px;
  } 

  .my-div5 {
    border: 2px solid red;
    width: 250px;
    height: 220px;
    padding 10px;
  } 
  .my-div6 {
    border: 2px solid red;
    width: 1000px;
    height: 300px;
    position: absolute; left: 180px; top: 350px;
  } 
  .my-div7 {
    border: 2px solid red;
    width: 300px;
    height: 50px;
    position: absolute; left: 180px; top: 250px;
  } 
  .my-div8 {
    border: 2px solid red;
    width: 1000px;
    height: 700px;
    position: absolute; left: 180px; top: 520px;
  } 


</style>
<head>
<div  class="my-div1" style="width: 1280px; height: 900px;">
  <div class="my-div1"style= "padding : 10px" >
  <tr style= "padding : 10px">
    <td class="my-div">
      <a href="{% url 'green:Initialize'%}">
      <img src="{% static 'img\G-AID1.png'%}">
      </a>
    </td>  
  <td class="my-div"style= "padding : 10px ">
      <img src="{% static 'img\Auto.png'%}"onclick="alert('Auto을 시작합니다.')">
    </td>
     <td class="my-div"style= "padding : 10px">
      <img src="{% static 'img\Manual.png'%}"onclick="alert('Manual을 열겠습니다.')">
    </td>
    <td class="my-div"style= "padding : 10px">
        <img src="{% static 'img\fill.png'%}">
      </td>
      <td class="my-div"style= "padding : 10px">
          <img src="{% static 'img\fill.png'%}">
        </td>
        <td class="my-div"style= "padding : 10px">
            <img src="{% static 'img\fill.png'%}">
          </td>
          <td class="my-div"style= "padding : 10px">
              <img src="{% static 'img\fill.png'%}">
            </td>
    <td class="my-div"style= "padding : 10px">
        <img src="{% static 'img\Log.png'%}" id="close" >
      </td>
    
  </tr>
  </div>

  <div class="my-div" style= "padding : 10px">
    <a href="{% url 'green:Jog'%}">
      <img src="{% static 'img\Jog.jpg'%}"></a>
  </div>  
    <div class="my-div"style= "padding : 10px" >
      <a href="{% url 'green:Spindle'%}">
        <img src="{% static 'img\Spindle.png'%}"></a>
    </div>  
      <div class="my-div"style= "padding : 10px">
        <a href="{% url 'green:Tool'%}">
          <img src="{% static 'img\Tool.png'%}"></a>
    </div>  
       <div class="my-div"style= "padding : 10px">
        <a href="{% url 'green:Maintenance'%}">
          <img src="{% static 'img\Maintenance.jpg'%}"></a>
    </div>

    
 
  </div>    
     
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Hello, django!</title>
</head>
<body style="background-color: black;">
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<div style="width: 1280px; height: 800px;">
  <div class="row container" style="height: 100%; width: 100%; margin: 0">
    <div class="col-sm-4 col-md-8 col-lg-12" style="height: 100%; width: 100%; margin: 0">
        {% block content %}
        {% endblock %}
    </div>
  </div>
</div>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<script>
  const close = document.getElementById('close');
  close.addEventListener("click", function() {
    alert("종료합니다");
  });
</script>
</body>

UI_UX/API/goo/templates/green/Initialize.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div style=" position: absolute; top: 450px; right: 1000px;">
    <a href="{% url 'green:Jog'%}">
      <img src="{% static 'img\Initialize.png'%}"></a>
    </div>
</div>  


{% endblock%}

UI_UX/API/goo/templates/green/Jog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .my-div10 {
        border: 2px solid red;
        width: 300px;
        height: 50px;
        position: absolute; left: 100px; top: 0px;
      } 
    .my-div11 {
        border: 2px solid red;
        width: 1100px;
        height: 720px;
        position: absolute; left: 180px; top: 180px;
      }
    .my-div100 {
      border: 2px solid red;
      width: 410px;
      height: 280px;
      position: absolute; left: 20px; top: 30px;
    }
    .my-div101 {
        border: 2px solid red;
        width: 410px;
        height: 280px;
        position: absolute; left: 600px; top: 30px;
    }

    .my-div102 {
    border: 2px solid red;
    width: 300px;
    height: 200px;
    position: absolute; left: 20px; top: 470px;
    }
    .my-div103 {
    border: 2px solid red;
    width: 500px;
    height: 235px;
    position: absolute; left: 550px; top: 470px;
    }


</style>

    <div class="my-div11">
        <div class="my-div100">
            <body>
                <table border="1" width="400" height="50" >
                    <tr>
                    <th><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jog Step</span></th>
                    <th><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Continuous</span></th>
                    <th><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ctn T</span></th>
                    </tr>
                    <tr>
                </table><br>
                <table border="1" width="400" height="200" >
                    <tr>                   
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.01</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.05</span></td>
                    </tr>
                    <tr>   
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.1</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.5</span></td>
                    </tr>
                    <tr>          
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unit Select</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.0000<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inc.Movement</span></td>
                    </tr>
                </table>
            </body>
        </div>
        <div class="my-div101">
            <body>
                <table border="1" width="400" height="270" >
                    <tr>
                    <th><span style="color: white;">Machine Position</span></th>
                    </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.0005</span></td>
                  </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Y</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-0.0005</span></td>
                    </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Z</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-0.0005</span></td>
                    </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.0005</span></td>
                    </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0.0000</span></td>
                    </tr>
                </table>
            </body>
        </div>
        <div class="my-div102">
            <body>
                <table border="1" width="300" height="200" >
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A-</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Y-</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A+</span></td>
                    </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X-</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;X+</span></td>
                    </tr>
                    <tr>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B-</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Y+</span></td>
                    <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B+</span></td>
                    </tr>
                    <tr>
                        <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Z+</span></td>
                        </tr>
                        <tr>
                        <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Z-</span></td>
                        </tr>
                </table>
            </body>
        </div>
        <div class="my-div103">
            <body>
                <table border="1" width="400" height="200" >
                    <tr>
                    <td> <img src="{% static 'img\Stop.png'%}"onclick="alert('이미지를 클릭했습니다!')"></td>
                    <td><img src="{% static 'img\stop.png'%}" onclick="alert('이미지를 클릭했습니다!')"></td>
                    </tr>
                    <tr>
                    <td><img src="{% static 'img\Stop.png'%}"onclick="alert('이미지를 클릭했습니다!')"></td>
                    <td><img src="{% static 'img\Stop.png'%}"onclick="alert('이미지를 클릭했습니다!')"></td>
                    </tr>
                    
                </table>
            </body>
        </div>
</div>

 
{% endblock%}

UI_UX/API/goo/templates/green/Maintenance.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!doctype html>
<html lang="ko">
  <style>
    .screen-transition {
      animation: slide-in 1.5s forwards;
    }
    
    @keyframes slide-in {
      from {
        transform: translateX(100%);
      }
      to {
        transform: translateX(0%);
      }
    }


  .pressable {
    transition: transform 0.1s;
    }
  
  .pressable:active {
    transform: translateY(50px);
    }

  .my-div {
    border: 2px solid red;
    width: 170px;
  }
  .my-div6 {
    border: 2px solid red;
    width: 200px;
    height: 700px;
    position: absolute; left: 180px; top: 175px;
  } 
  .my-div7 {
    border: 2px solid red;
    width: 240x;
    height: 700px;
    position: absolute; left: 380px; top: 175px;
  } 
  .my-div8{
    border: 5px solid red;
    width: 600px;
    height: 150px;
    position: absolute; left: 680px; top: 730px;
  } 

  
</style>
<head>
    <div class="my-div6"style= "padding : 10px">
        <tr>
          <td style= "width: 50%;">
            <img src="{% static 'img\coolant oil2.png'%}"onclick="alert('오일을 분배합니다.')">
            <span style="color: #ffffff;" >Coolant Oil</span>
          </td>
          <td style= "width: 50%;">
              <img src="{% static 'img\coolant water2.png'%}"onclick="alert('냉각수를 실행합니다.')">
              <span  style="color: #ffffff;">Coolant Water</span>
            </td>
          </tr>
            <tr>
              <td>
                <img src="{% static 'img\coolant air2.png'%}"onclick="alert('공기식 냉각을 실행합니다.')">
                <span style="color: #ffffff;" >Coolant Air</span>
              </td>
              <td>
                  <img src="{% static 'img\air blow2.png'%}"onclick="alert('냉각 분사을 실행합니다.')">
                  <span style="color: #ffffff;" >Coolant Blow</span>
                </td>
                </tr>
                <td>
                    <img src="{% static 'img\spindle purge.png'%}"onclick="alert('주축 클리닝을 실행합니다.')">
                    <span style="color: #ffffff;">Spindle purge</span>
                  </td>
                  </tr>
        </div>     
        <div class="my-div7"style= "padding : 10px">
          <tr>
            <td style= "width: 50%;">
              <img src="{% static 'img\ATC door.png'%}"onclick="alert('도구를 교환합니다.')">
              <span style="position: relative; top: -10px; left: -170px; color: #ffffff;">ATC Door</span>
            </td>
            <td style= "width: 50%;">
                <img src="{% static 'img\home.png'%}"onclick="alert('HOME으로 이동합니댜.')">
                <span style="position: relative; top: -10px; left: -170px; color: #ffffff;">HoME</span>
              </td>
            </tr>
                <td>
                    <img src="{% static 'img\nozzle.png'%}"onclick="alert('분사합니다.')">
                    <span style="position: relative; top: -10px; left: -170px; color: #ffffff;">Nozzle</span>
                  </td>
                  </tr>
                  <tr>
                    <td style= "width: 50%;">
                      <img src="{% static 'img\LED.png'%}"onclick="alert('조명을 선택합니다.')">
                    </td>
          </div>  
          <div class="my-div8"style= "padding : 10px">
                 <td>
                      <img src="{% static 'img\Save.png'%}"onclick="alert('저장하겠습니다.')">
                    </td>
                    </tr>
                    <tr>
                      <td style= "width: 50%;">
                        <img src="{% static 'img\Close.png'%}"onclick="alert('창을 닫게습니다.')">
                      </td>
            </div>  
    </div>    
       
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
      <!-- pybo CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
      <title>Hello, django!</title>
  </head>
  <body style="background-color: black;">
  <!-- 기본 템플릿 안에 삽입될 내용 Start -->
  <div style="width: 1280px; height: 800px;">
    <div class="row container" style="height: 100%; width: 100%; margin: 0">
      <div class="col-sm-4 col-md-8 col-lg-12" style="height: 100%; width: 100%; margin: 0">
          {% endblock %}
      </div>
    </div>
  </div>
  <!-- 기본 템플릿 안에 삽입될 내용 End -->
  </body>

UI_UX/API/goo/templates/green/Spindle.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
  .my-div10 {
    width: 300px;
    height: 50px;
    position: absolute; left: 100px; top: 0px;
  } 
  .my-div11 {
    border: 2px solid red;
    width: 1050px;
    height: 700px;
    position: absolute; left: 100px; top: 200px;
  }
  .my-div12 {
    border: 2px solid red;
    width: 520px;
    height: 130px;
    position: absolute; left: 530px; top:60px;
  }
  .my-div13 {
    border: 2px solid red;
    width: 250px;
    height: 130px;
    position: absolute; left: 785px; top:190px;
  }
  .my-div14 {
    border: 2px solid red;
    width: 250px;
    height: 130px;
    position: absolute; left: 785px; top:320px;
  }
  .my-div15 {
    border: 2px solid red;
    width: 250px;
    height: 90px;
    position: absolute; left: 785px; top:600px;
  }
  .my-div16 {
    border: 2px solid red;
    width: 400px;
    height: 230px;
    position: absolute; left: 380px; top:190px;
  }
  .my-div17 {
    border: 2px solid red;
    width: 355px;
    height: 505px;
    position: absolute; left: 0px; top:190px;
  }
  .my-div18 {
    border: 2px solid red;
    width: 355px;
    height: 105px;
    position: absolute; left: 0px; top:0px;
  }
  .my-div19 {
    border: 2px solid red;
    width: 400px;
    height: 205px;
    position: absolute; left: 380px; top:450px;
  }    
</style>
<script>
  function increaseNumber() {
    var numberInput = document.getElementById("numberInput");
    var currentValue = parseInt(numberInput.value);
    numberInput.value = currentValue + 1000;
  }
  
  function decreaseNumber() {
    var numberInput = document.getElementById("numberInput");
    var currentValue = parseInt(numberInput.value);
    if (currentValue > 0) {
      numberInput.value = currentValue - 1000;
    }
  }
</script>
  </script>
<div class="my-div10" >
    <div  class="my-div11">
        <div >
            <div class="my-div18">
              <body>
                <span style="color: white;">Max RPM</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text=" id="numberInput" value="30000" style="width: 100px;"><br>
                <span style="color: white;">Current RPM</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text=" id="numberInput1" value="0" style="width: 100px;"><button type="button" onclick="Numberplus()">▲</button><br>
                <span style="color: white;">Change RPM</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input type="text=" id="numberInput2" value="1000" style="width: 100px;"> <button type="button" onclick="Numberminus()">▼</button>
              </body>
            
              
            <div class="my-div12">
                <img src="{% static 'img\Start.png'%}"onclick="alert('시작합니다.')">
                    <img src="{% static 'img\Stop.png'%}"onclick="alert('종료합니다.')"><br>
            </div>
            <div class="my-div13">   
                        <img src="{% static 'img\Warmingup.png'%}"onclick="alert('warmingup합니다.')">
                    </div>
            </div>
          </div>
          
        <div class="my-div16">
          <body>
            <table border="1" width="400" height="200" >
              <tr>
                <th></th>
                <th><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RPM</span></th>
                <th><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Time(min)</span></th>
              </tr>
              <tr>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Step1</span></td>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;15,000</span></td>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3</span></td>
              </tr>
              <tr>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Step2</span></td>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;22,500</span></td>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5</span></td>
              </tr>
              <tr>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Step3</span></td>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;27,000</span></td>
                <td><span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2</span></td>
              </tr>
            </table>
          </body>
        </div>
        <div class="my-div17">
          <span style="color: white;"><h1>&nbsp;&nbsp;After - 4 Hours</h1></span>
              <img src="{% static 'img\white spindle.png'%}"style="width:350px; height:400px;">
          </div>

            <div class="my-div14">
                <img src="{% static 'img\w.Stop.png'%}"onclick="alert('warmingup 종료합니다.')"></a>
            </div>
            <div class="my-div15">
                    <img src="{% static 'img\Close.png'%}"onclick="alert('창을 닫게습니다.')" style="width:250px; height:80px;">
                </div>       
                <div class="my-div19">
                
                  <span style="color: white;">&nbsp;&nbsp;&nbsp;&nbsp;Purge</span>

                </div>
      </div>
  </div>
  <script>
    const numberInput = document.getElementById('numberInput');
    const numberInput1 = document.getElementById('numberInput1');
    var numbercnt = 30000;
    var numbercnt1 = 0;

    function Numberplus() {
    numbercnt1= numbercnt1 +1000;
    numberInput.value = numbercnt;
    numberInput1.value = numbercnt1;
    }

    function Numberminus() {
    if (numbercnt1 != 0) {
        numbercnt1= numbercnt1 -1000;
    }
    numberInput.value = numbercnt;
    numberInput1.value = numbercnt1;
    }
</script>  
{% endblock %}


  

  